### ISSUE TITLE
TO DO

### ISSUE THREAD

**Issue by ghost** [dwyl/learn-html5#17]
Hi! Can i add info about the first TO DO: div and span?
Thanks!

**Comment by iteles** [comment]
@edwardcodes Do you mean you'd like to work on #8 ?

If so, no need to create a new issue for it as one already exists 😊 . I would recommend:
+ Add a `duplicate` label to this issue and close it 
+ #8 [has already been validated](https://github.com/dwyl/contributing#why-does-the-issue-need-to-be-validated--one-word-communication) as a requirement so you can start working on it:
  + Begin your work, remembering to follow our [contributing process](https://github.com/dwyl/contributing) as you go - I think we're at about [this stage](https://github.com/dwyl/contributing#part-3-do-the-work) of the process

**Comment by ghost** [comment]
@iteles yes i would, I will close this issue and follow the contributing process, thank you!
( can´t add the duplicate label, don´t know why..)

**Comment by iteles** [comment]
Ah, permissions. @edwardcodes you should be able to from now on!
