### ISSUE TITLE
XP with html

### ISSUE THREAD

**Issue by karinakozarova** [dwyl/learn-html5#4]
As the guide is called learn html5, should we think that the end-user (the one who will actually read it) will know html and we need to teach him just the differences or is our user with no experience with html at all?

**Comment by karinakozarova** [comment]
@nelsonic

**Comment by nelsonic** [comment]
@karinakozarova we should _expect_ that the person has never written _any_ HTML and they are starting from scratch with what a "tag" is... 
IMO this is one of the most _difficult_ tutorials/introductions to write because we cannot assume _any_ prior knowledge. 🤔

**Comment by karinakozarova** [comment]
So it should be just plain HTML5, no CSS? Or maybe should include a little about CSS.

**Comment by nelsonic** [comment]
@karinakozarova great question! when we have taught HTML in workshops we always include a bit of CSS but I think it will be towards the _end_ of the tutorial as we want to have a _separate_ CSS tutorial which in turn links to https://github.com/dwyl/learn-tachyons 😉 
You may not have seen our "roadmap" of tutorials: https://github.com/dwyl/the-book/issues/69
